permissions:
  contents: read
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-secrets:
    name: Validate Secrets
    runs-on: ubuntu-latest
    # Only run secret validation on push to main, not on PRs
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Check required secrets
      run: |
        echo "Checking required secrets..."
        
        if [ -z "${{ secrets.AWS_ACCESS_KEY_ID }}" ]; then
          echo "❌ AWS_ACCESS_KEY_ID secret is missing"
          exit 1
        else
          echo "✅ AWS_ACCESS_KEY_ID is set"
        fi
        
        if [ -z "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ]; then
          echo "❌ AWS_SECRET_ACCESS_KEY secret is missing"
          exit 1
        else
          echo "✅ AWS_SECRET_ACCESS_KEY is set"
        fi
        
        if [ -z "${{ secrets.API_KEY }}" ]; then
          echo "❌ API_KEY secret is missing"
          exit 1
        else
          echo "✅ API_KEY is set"
        fi
        
        if [ -z "${{ secrets.SITE_ID }}" ]; then
          echo "❌ SITE_ID secret is missing"
          exit 1
        else
          echo "✅ SITE_ID is set"
        fi
        
        echo "🎉 All required secrets are configured!"

  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    
    - name: Setup Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 black pytest
    
    - name: Lint with flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
    
    - name: Format check with black
      run: black --check .
    
    - name: Validate Python files
      run: |
        python -m py_compile morning_config.py
        python -m py_compile evening_config.py

  terraform-check:
    name: Terraform Check
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: terraform
    
    steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
      with:
        terraform_version: 1.5.0
    
    - name: Terraform Format Check
      run: terraform fmt -check -recursive
    
    - name: Terraform Init
      run: terraform init -backend=false
    
    - name: Terraform Validate
      run: terraform validate